#!/bin/sh
# $Id: files_nemuvideo_drm $
## @file
# Shared file between Makefile.kmk and export_modules
#

#
# Copyright (C) 2007-2010 Oracle Corporation
#
# This file is part of VirtualBox Open Source Edition (OSE), as
# available from http://www.virtualbox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualBox OSE distribution. VirtualBox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

FILES_NEMUVIDEO_DRM_NOBIN=" \
    ${PATH_ROOT}/src/Nemu/Additions/freebsd/drm/nemuvideo_drm.c=>nemuvideo_drm.c \
    ${PATH_ROOT}/src/Nemu/Additions/freebsd/drm/Makefile=>Makefile \
"

FILES_NEMUVIDEO_DRM_BIN=" \
"
