#!/bin/sh
# $Id$
## @file
# Reloads the new kernel extension at the end of installation.
#

#
# Copyright (C) 2007-2015 Oracle Corporation
#
# This file is part of VirtualBox Open Source Edition (OSE), as
# available from http://www.virtualbox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualBox OSE distribution. VirtualBox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

#
# Make sure the old startup items are gone.
#
if [ -d /Library/StartupItems/VirtualBox/ ]; then 
    rm -vf  "/Library/StartupItems/VirtualBox/StartupParameters.plist"
    rm -vf  "/Library/StartupItems/VirtualBox/VirtualBox"
    rm -vf  "/Library/StartupItems/VirtualBox/Resources/English.lproj/Localizable.strings"
    test -d "/Library/StartupItems/VirtualBox/Resources/English.lproj/" && rmdir "/Library/StartupItems/VirtualBox/Resources/English.lproj/"
    test -d "/Library/StartupItems/VirtualBox/Resources/"               && rmdir "/Library/StartupItems/VirtualBox/Resources/"
    test -d "/Library/StartupItems/VirtualBox/"                         && rmdir "/Library/StartupItems/VirtualBox/"
fi

#
# Make sure old kernel extensions are gone (moved to "/Library/Application Support/VirtualBox/" with 4.3).
#
rm -Rfv \
    "/Library/Extensions/NemuDrv.kext/" \
    "/Library/Extensions/NemuNetFlt.kext/" \
    "/Library/Extensions/NemuNetAdp.kext/" \
    "/Library/Extensions/NemuUSB.kext/" \
    "/Library/Extensions/NemuDrvTiger.kext/" \
    "/Library/Extensions/NemuUSBTiger.kext/"

#
# Install the launchd script.
#
# Make sure "/Library/LaunchDaemons/ exists first as some uninstallers/users
# may be silly enough to remove it.  We assume that /Library exists and will
# not try create it because it normally has extra ACLs.
#
if [ ! -e "/Library/LaunchDaemons/" ]; then
    set -e
    mkdir "/Library/LaunchDaemons"
    chmod 755 "/Library/LaunchDaemons"
    chown root:wheel "/Library/LaunchDaemons"
    set +e
fi
rm -vf "/Library/LaunchDaemons/org.virtualbox.startup.plist"
set -e
ln -s  "../Application Support/VirtualBox/LaunchDaemons/org.virtualbox.startup.plist" \
       "/Library/LaunchDaemons/org.virtualbox.startup.plist"
set +e

#
# Unload any old extension that might be loaded already (ignore failures).
#
sync
if kextstat -lb org.virtualbox.kext.NemuNetAdp 2>&1 | grep -q org.virtualbox.kext.NemuNetAdp; then
    kextunload -m org.virtualbox.kext.NemuNetAdp
fi
if kextstat -lb org.virtualbox.kext.NemuNetFlt 2>&1 | grep -q org.virtualbox.kext.NemuNetFlt; then
    kextunload -m org.virtualbox.kext.NemuNetFlt
fi
if kextstat -lb org.virtualbox.kext.NemuUSB 2>&1 | grep -q org.virtualbox.kext.NemuUSB; then
    kextunload -m org.virtualbox.kext.NemuUSB
fi
if kextstat -lb org.virtualbox.kext.NemuDrv 2>&1 | grep -q org.virtualbox.kext.NemuDrv; then
    kextunload -m org.virtualbox.kext.NemuDrv
fi

#
# Load the extension, exit on first error.
#
sync
set -e
kextload    '/Library/Application Support/VirtualBox/NemuDrv.kext'
kextload -d '/Library/Application Support/VirtualBox/NemuDrv.kext'  '/Library/Application Support/VirtualBox/NemuUSB.kext'
kextload -d '/Library/Application Support/VirtualBox/NemuDrv.kext'  '/Library/Application Support/VirtualBox/NemuNetFlt.kext'
kextload -d '/Library/Application Support/VirtualBox/NemuDrv.kext'  '/Library/Application Support/VirtualBox/NemuNetAdp.kext'

