#!/bin/sh
# $Id: files_nemusf $
## @file
# Shared file between Makefile.kmk and export_modules
#

#
# Copyright (C) 2007-2010 Oracle Corporation
#
# This file is part of VirtualBox Open Source Edition (OSE), as
# available from http://www.virtualbox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualBox OSE distribution. VirtualBox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

FILES_NEMUSF_NOBIN=" \
    ${PATH_ROOT}/include/iprt/nocrt/limits.h=>include/iprt/nocrt/limits.h \
    ${PATH_ROOT}/include/iprt/alloc.h=>include/iprt/alloc.h \
    ${PATH_ROOT}/include/iprt/asm.h=>include/iprt/asm.h \
    ${PATH_ROOT}/include/iprt/asm-amd64-x86.h=>include/iprt/asm-amd64-x86.h \
    ${PATH_ROOT}/include/iprt/asm-math.h=>include/iprt/asm-math.h \
    ${PATH_ROOT}/include/iprt/assert.h=>include/iprt/assert.h \
    ${PATH_ROOT}/include/iprt/cdefs.h=>include/iprt/cdefs.h \
    ${PATH_ROOT}/include/iprt/err.h=>include/iprt/err.h \
    ${PATH_ROOT}/include/iprt/fs.h=>include/iprt/fs.h \
    ${PATH_ROOT}/include/iprt/latin1.h=>include/iprt/latin1.h \
    ${PATH_ROOT}/include/iprt/log.h=>include/iprt/log.h \
    ${PATH_ROOT}/include/iprt/mangling.h=>include/iprt/mangling.h \
    ${PATH_ROOT}/include/iprt/mem.h=>include/iprt/mem.h \
    ${PATH_ROOT}/include/iprt/param.h=>include/iprt/param.h \
    ${PATH_ROOT}/include/iprt/path.h=>include/iprt/path.h \
    ${PATH_ROOT}/include/iprt/semaphore.h=>include/iprt/semaphore.h \
    ${PATH_ROOT}/include/iprt/stdarg.h=>include/iprt/stdarg.h \
    ${PATH_ROOT}/include/iprt/stdint.h=>include/iprt/stdint.h \
    ${PATH_ROOT}/include/iprt/string.h=>include/iprt/string.h \
    ${PATH_ROOT}/include/iprt/time.h=>include/iprt/time.h \
    ${PATH_ROOT}/include/iprt/types.h=>include/iprt/types.h \
    ${PATH_ROOT}/include/iprt/uni.h=>include/iprt/uni.h \
    ${PATH_ROOT}/include/iprt/utf16.h=>include/iprt/utf16.h \
    ${PATH_ROOT}/include/Nemu/cdefs.h=>include/Nemu/cdefs.h \
    ${PATH_ROOT}/include/Nemu/err.h=>include/Nemu/err.h \
    ${PATH_ROOT}/include/Nemu/hgcmsvc.h=>include/Nemu/hgcmsvc.h \
    ${PATH_ROOT}/include/Nemu/log.h=>include/Nemu/log.h \
    ${PATH_ROOT}/include/Nemu/ostypes.h=>include/Nemu/ostypes.h \
    ${PATH_ROOT}/include/Nemu/param.h=>include/Nemu/param.h \
    ${PATH_ROOT}/include/Nemu/shflsvc.h=>include/Nemu/shflsvc.h \
    ${PATH_ROOT}/include/Nemu/types.h=>include/Nemu/types.h \
    ${PATH_ROOT}/include/Nemu/NemuGuest.h=>include/Nemu/NemuGuest.h \
    ${PATH_ROOT}/include/Nemu/NemuGuest2.h=>include/Nemu/NemuGuest2.h \
    ${PATH_ROOT}/include/Nemu/NemuGuestLib.h=>include/Nemu/NemuGuestLib.h \
    ${PATH_ROOT}/include/Nemu/NemuGuestLibSharedFolders.h=>include/Nemu/NemuGuestLibSharedFolders.h \
    ${PATH_ROOT}/include/Nemu/NemuGuestMangling.h=>include/Nemu/NemuGuestMangling.h \
    ${PATH_ROOT}/include/Nemu/VMMDev.h=>include/Nemu/VMMDev.h \
    ${PATH_ROOT}/include/Nemu/VMMDev2.h=>include/Nemu/VMMDev2.h \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/GenericRequest.cpp=>GenericRequest.c \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/HGCM.cpp=>HGCM.c \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/Init.cpp=>Init.c \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/PhysHeap.cpp=>PhysHeap.c \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/SysHlp.cpp=>SysHlp.c \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/SysHlp.h=>SysHlp.h \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/VBGLInternal.h=>VBGLInternal.h \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/NemuGuestR0LibSharedFolders.c=>NemuGuestR0LibSharedFolders.c \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/NemuGuestLog.h=>NemuGuestLog.h \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/VMMDev.cpp=>VMMDev.c \
    ${PATH_ROOT}/src/Nemu/Additions/common/NemuGuestLib/VbglR0CanUsePhysPageList.cpp=>VbglR0CanUsePhysPageList.c \
    ${PATH_ROOT}/src/Nemu/Installer/linux/Makefile.include.header=>Makefile.include.header \
    ${PATH_ROOT}/src/Nemu/Installer/linux/Makefile.include.footer=>Makefile.include.footer \
    ${PATH_ROOT}/src/Nemu/Runtime/common/math/gcc/divdi3.c=>divdi3.c \
    ${PATH_ROOT}/src/Nemu/Runtime/common/math/gcc/moddi3.c=>moddi3.c \
    ${PATH_ROOT}/src/Nemu/Runtime/common/math/gcc/qdivrem.c=>qdivrem.c \
    ${PATH_ROOT}/src/Nemu/Runtime/common/math/gcc/quad.h=>quad.h \
    ${PATH_ROOT}/src/Nemu/Runtime/common/math/gcc/udivdi3.c=>udivdi3.c \
    ${PATH_ROOT}/src/Nemu/Runtime/common/math/gcc/umoddi3.c=>umoddi3.c \
    ${PATH_ROOT}/src/Nemu/Runtime/r0drv/linux/the-linux-kernel.h=>r0drv/linux/the-linux-kernel.h \
    ${PATH_ROOT}/src/Nemu/Additions/linux/sharedfolders/Makefile.module=>Makefile \
    ${PATH_ROOT}/src/Nemu/Additions/linux/sharedfolders/dirops.c=>dirops.c \
    ${PATH_ROOT}/src/Nemu/Additions/linux/sharedfolders/lnkops.c=>lnkops.c \
    ${PATH_ROOT}/src/Nemu/Additions/linux/sharedfolders/regops.c=>regops.c \
    ${PATH_ROOT}/src/Nemu/Additions/linux/sharedfolders/utils.c=>utils.c \
    ${PATH_ROOT}/src/Nemu/Additions/linux/sharedfolders/vbsfmount.h=>vbsfmount.h \
    ${PATH_ROOT}/src/Nemu/Additions/linux/sharedfolders/vfsmod.c=>vfsmod.c \
    ${PATH_ROOT}/src/Nemu/Additions/linux/sharedfolders/vfsmod.h=>vfsmod.h \
    ${PATH_OUT}/version-generated.h=>version-generated.h \
    ${PATH_OUT}/product-generated.h=>product-generated.h \
"

FILES_NEMUSF_BIN=" \
"
